// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Database;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseService))]
    [Migration("20221116143457_v4")]
    partial class v4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.5.22302.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Content")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8759465-565d-4e4f-9904-48a44fec4bc1"),
                            Author = "Author 1",
                            Content = "Comment 1 about post 1",
                            CreationDate = new DateTime(2022, 11, 16, 14, 34, 57, 522, DateTimeKind.Local).AddTicks(5212),
                            PostId = new Guid("18461bb0-d8a4-425a-97d7-cc0338462c1c")
                        },
                        new
                        {
                            Id = new Guid("8d0cfc25-936b-4217-b3a2-89063f9b788c"),
                            Author = "Author 2",
                            Content = "Comment 2 about post 1",
                            CreationDate = new DateTime(2022, 11, 16, 14, 34, 57, 522, DateTimeKind.Local).AddTicks(5483),
                            PostId = new Guid("18461bb0-d8a4-425a-97d7-cc0338462c1c")
                        },
                        new
                        {
                            Id = new Guid("8de1b74f-a5d4-4859-96da-51f0e5919118"),
                            Author = "Author 3",
                            Content = "Comment 1 about post 2",
                            CreationDate = new DateTime(2022, 11, 16, 14, 34, 57, 522, DateTimeKind.Local).AddTicks(5492),
                            PostId = new Guid("2ce103ca-87f2-4b7b-b51d-aadb2d203ed7")
                        },
                        new
                        {
                            Id = new Guid("9791b85b-97a3-43bf-944b-289f4bbd5757"),
                            Author = "Author 4",
                            Content = "Comment 2 about post 2",
                            CreationDate = new DateTime(2022, 11, 16, 14, 34, 57, 522, DateTimeKind.Local).AddTicks(5502),
                            PostId = new Guid("2ce103ca-87f2-4b7b-b51d-aadb2d203ed7")
                        },
                        new
                        {
                            Id = new Guid("114e2d7e-c71c-4a2b-bd5e-9807895a3ea5"),
                            Author = "Author 5",
                            Content = "Comment 1 about post 3",
                            CreationDate = new DateTime(2022, 11, 16, 14, 34, 57, 522, DateTimeKind.Local).AddTicks(5504),
                            PostId = new Guid("4775adb5-c2dc-479d-ab20-f1cd24e38769")
                        },
                        new
                        {
                            Id = new Guid("8785cc95-5c34-4379-919f-ec6366135de8"),
                            Author = "Author 6",
                            Content = "Comment 2 about post 3",
                            CreationDate = new DateTime(2022, 11, 16, 14, 34, 57, 522, DateTimeKind.Local).AddTicks(5509),
                            PostId = new Guid("4775adb5-c2dc-479d-ab20-f1cd24e38769")
                        });
                });

            modelBuilder.Entity("Model.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18461bb0-d8a4-425a-97d7-cc0338462c1c"),
                            Content = "Content 1",
                            CreationDate = new DateTime(2022, 11, 16, 14, 34, 57, 519, DateTimeKind.Local).AddTicks(4875),
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = new Guid("2ce103ca-87f2-4b7b-b51d-aadb2d203ed7"),
                            Content = "Content 2",
                            CreationDate = new DateTime(2022, 11, 16, 14, 34, 57, 522, DateTimeKind.Local).AddTicks(3164),
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = new Guid("4775adb5-c2dc-479d-ab20-f1cd24e38769"),
                            Content = "Content 3",
                            CreationDate = new DateTime(2022, 11, 16, 14, 34, 57, 522, DateTimeKind.Local).AddTicks(3184),
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = new Guid("052fd34a-1073-4f8c-acbc-0186334ae88c"),
                            Content = "Content 4",
                            CreationDate = new DateTime(2022, 11, 16, 14, 34, 57, 522, DateTimeKind.Local).AddTicks(3187),
                            Title = "Post 4"
                        },
                        new
                        {
                            Id = new Guid("71e333ec-a5b5-42ac-a147-c9b6c5daa4c2"),
                            Content = "Content 5",
                            CreationDate = new DateTime(2022, 11, 16, 14, 34, 57, 522, DateTimeKind.Local).AddTicks(3190),
                            Title = "Post 5"
                        });
                });

            modelBuilder.Entity("Model.Comment", b =>
                {
                    b.HasOne("Model.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Model.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
