// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Database;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20221116120313_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.5.22302.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Model.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29754764-e588-422d-b401-4e80c20c6da0"),
                            Content = "Content 1",
                            CreationDate = new DateTime(2022, 11, 16, 12, 3, 13, 437, DateTimeKind.Local).AddTicks(8818),
                            Title = "Title 1"
                        },
                        new
                        {
                            Id = new Guid("83aefff7-8863-4c3a-8059-7b3d79512851"),
                            Content = "Content 2",
                            CreationDate = new DateTime(2022, 11, 16, 12, 3, 13, 440, DateTimeKind.Local).AddTicks(7260),
                            Title = "Title 2"
                        },
                        new
                        {
                            Id = new Guid("bd8b9194-f31d-4fd6-b438-a5e2187ebf5e"),
                            Content = "Content 3",
                            CreationDate = new DateTime(2022, 11, 16, 12, 3, 13, 440, DateTimeKind.Local).AddTicks(7291),
                            Title = "Title 3"
                        },
                        new
                        {
                            Id = new Guid("1931e43a-843b-426f-b8fb-dd26504f345f"),
                            Content = "Content 4",
                            CreationDate = new DateTime(2022, 11, 16, 12, 3, 13, 440, DateTimeKind.Local).AddTicks(7295),
                            Title = "Title 4"
                        },
                        new
                        {
                            Id = new Guid("30102fec-d70a-43f9-b531-67d23b4bf7e2"),
                            Content = "Content 5",
                            CreationDate = new DateTime(2022, 11, 16, 12, 3, 13, 440, DateTimeKind.Local).AddTicks(7297),
                            Title = "Title 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
