// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Database;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.5.22302.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37a7f095-b237-4204-89ed-363787a0cfcb"),
                            Author = "Author 1",
                            Content = "Comment 1 about post 1",
                            CreationDate = new DateTime(2022, 11, 18, 13, 33, 36, 583, DateTimeKind.Local).AddTicks(149),
                            PostId = new Guid("3a152e48-b365-4114-9ca3-25afa4c1a76d")
                        },
                        new
                        {
                            Id = new Guid("aa85ee15-ba73-4d93-8f09-94ba0d7b0d5a"),
                            Author = "Author 2",
                            Content = "Comment 2 about post 1",
                            CreationDate = new DateTime(2022, 11, 18, 13, 33, 36, 583, DateTimeKind.Local).AddTicks(410),
                            PostId = new Guid("3a152e48-b365-4114-9ca3-25afa4c1a76d")
                        },
                        new
                        {
                            Id = new Guid("5c747e1f-d2b5-4ae9-951d-40fd3b5b12b0"),
                            Author = "Author 3",
                            Content = "Comment 1 about post 2",
                            CreationDate = new DateTime(2022, 11, 18, 13, 33, 36, 583, DateTimeKind.Local).AddTicks(419),
                            PostId = new Guid("b455c60e-08ba-4d21-8fdd-a1d9fcdbbcde")
                        },
                        new
                        {
                            Id = new Guid("e4c9f408-db16-4085-9818-4a70e11806d0"),
                            Author = "Author 4",
                            Content = "Comment 2 about post 2",
                            CreationDate = new DateTime(2022, 11, 18, 13, 33, 36, 583, DateTimeKind.Local).AddTicks(422),
                            PostId = new Guid("b455c60e-08ba-4d21-8fdd-a1d9fcdbbcde")
                        },
                        new
                        {
                            Id = new Guid("0007c4a2-ce35-4bce-a9b1-2c7fef8bc698"),
                            Author = "Author 5",
                            Content = "Comment 1 about post 3",
                            CreationDate = new DateTime(2022, 11, 18, 13, 33, 36, 583, DateTimeKind.Local).AddTicks(425),
                            PostId = new Guid("2224e45a-138f-4ccc-981f-181104027f46")
                        },
                        new
                        {
                            Id = new Guid("2befe4a4-02e8-4a4a-a09a-0e35a6c23440"),
                            Author = "Author 6",
                            Content = "Comment 2 about post 3",
                            CreationDate = new DateTime(2022, 11, 18, 13, 33, 36, 583, DateTimeKind.Local).AddTicks(430),
                            PostId = new Guid("2224e45a-138f-4ccc-981f-181104027f46")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a152e48-b365-4114-9ca3-25afa4c1a76d"),
                            Content = "Content 1",
                            CreationDate = new DateTime(2022, 11, 18, 13, 33, 36, 580, DateTimeKind.Local).AddTicks(1118),
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = new Guid("b455c60e-08ba-4d21-8fdd-a1d9fcdbbcde"),
                            Content = "Content 2",
                            CreationDate = new DateTime(2022, 11, 18, 13, 33, 36, 582, DateTimeKind.Local).AddTicks(8167),
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = new Guid("2224e45a-138f-4ccc-981f-181104027f46"),
                            Content = "Content 3",
                            CreationDate = new DateTime(2022, 11, 18, 13, 33, 36, 582, DateTimeKind.Local).AddTicks(8186),
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = new Guid("5a6dfb41-08e3-49da-97b6-a94e63a93bc6"),
                            Content = "Content 4",
                            CreationDate = new DateTime(2022, 11, 18, 13, 33, 36, 582, DateTimeKind.Local).AddTicks(8198),
                            Title = "Post 4"
                        },
                        new
                        {
                            Id = new Guid("04a6be26-0eeb-49e1-92c9-97b15fba1066"),
                            Content = "Content 5",
                            CreationDate = new DateTime(2022, 11, 18, 13, 33, 36, 582, DateTimeKind.Local).AddTicks(8201),
                            Title = "Post 5"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.HasOne("Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
